name: containerAction
description: calculator to test container Action
inputs:
  number1:
    required: true
    default: 0
  number2:
    required: true
    default: 0
outputs:
  result:
    description: "output of sum of the 2 numbers"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.number1 }}
    - ${{ inputs.number2 }}
